### ISSUE TITLE
[INGEN] generated instances are invalid - attributes have 2 occurences whereas OPT tells 0..1.

### ISSUE THREAD

**Issue by jkryszyn** [ppazos/openEHR-OPT#149] opened 2023-01-03 13:05 UTC
Hello,
I am trying to generate instances of ePrescription (FHIR) (https://ckm.openehr.org/ckm/templates/1013.26.80). `INVAL` validates those instances against provided OPT, but when I try to upload such an instance to EHRServer or EHRbase, I get errors. EHRbase is more descriptive, below you can find its response:

>{"error":"Bad Request","message":"/content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0113]/items[openEHR-EHR-CLUSTER.medication_course_summary.v0 and name/value='Course summary']/items[at0002 and name/value='Date ordered/recommended']: Attribute has 2 occurrences, but must be 0..1, /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0113]/items[openEHR-EHR-CLUSTER.medication_course_summary.v0 and name/value='Course summary']/items[at0002 and name/value='Date ordered/recommended']: Attribute has 2 occurrences, but must be 0..1"}

Could you please check this issue?

**Comment by jkryszyn** [comment] 2023-01-03 14:15
Maybe a little more info:

I have provided a link to the OPT. An exemplary instance created by `INGEN` from this OPT using the following command

`./opt.sh ingen  path/to/ePrescription.opt path/to/files 1000 json version`

can be found here: [eprescription_(fhir)_20230103010156_000001_1.txt](https://github.com/ppazos/openEHR-OPT/files/10337210/eprescription_.fhir._20230103010156_000001_1.txt)

When I remove lines 938-956, i.e. a repeated `Date ordered/recommended` attribute, an instance is accepted by openEHR servers.

**Comment by ppazos** [comment] 2023-01-23 14:59
@jkryszyn we have a maintenance round for this repo next week, I will add this issue to my backlog and get it sorted out ASAP.

**Comment by ppazos** [comment] 2023-02-20 03:20
Might be fixed by https://github.com/ppazos/openEHR-OPT/commit/a4b62304e5ed82ee18e48bf8978dd502254edc8c

@jkryszyn can you verify we it's working and we can close this issue? Thanks.

**Comment by jkryszyn** [comment] 2023-02-20 09:30
The error is still there and the error message from EHRbase is the same. I have pulled the newest commit, deleted `build` directory and launched `gradle build -x test` before checking.

>{
    "error": "Unprocessable Entity",
    "message": "/content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0113]/items[openEHR-EHR-CLUSTER.medication_course_summary.v0 and name/value='Course summary']/items[at0002 and name/value='Date ordered/recommended']: Attribute has 2 occurrences, but must be 0..1, /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0113]/items[openEHR-EHR-CLUSTER.medication_course_summary.v0 and name/value='Course summary']/items[at0002 and name/value='Date ordered/recommended']: Attribute has 2 occurrences, but must be 0..1"
}

**Comment by ppazos** [comment] 2023-02-20 18:47
@jkryszyn I understood a little bit more the OPT structure:

1. inside CLUSTER at0113 you have CLUSTER medication_course_summary
2. medication_course_summary hast 3 items:
   1. ELEMENT at0001 name = Status with occurrences 0..1
   2. ELEMENT at0002 name = Date discontinued with occurrences 0..1
   3. ELEMENT at0002 name = Date written with occurrences 0..1

First there is a modeling issue: the ELEMENT at0002 (both nodes) have a DV_CODED_TEXT constraint in the name, which constraints the defining_code to a list of codes that mean different things, but the DV_CODED_TEXT value is fixed to "Date discontinued" or "Date written", that is semantically incorrect, since the codes are for:

1. Date ordered/recommended at0003
2. Date first prescription issued at0004
3. Date last prescription issued at0005
4. ...

So, the defining_code SHOULD match the meaning of the value in the coded text.

What the instance generator is doing is getting the first code in the list and creating a node, for both at0002 nodes, and using the 'value' from the term definition that matches that code, not using the constraint in the value.

Then about validation, it is not valid to have two sibling nodes with the same node ID (at0002) that also have the same value for the name. The name in ADL 1.4 is a way to differentiate siblings with the same node ID.


If I remove some code options from the first at0002 element I can get different values for the name, which should validate:

```
                                            {
                                                "_type": "ELEMENT",
                                                "name": {
                                                    "_type": "DV_CODED_TEXT",
                                                    "value": "Date last prescription issued",
                                                    "defining_code": {
                                                        "terminology_id": {
                                                            "_type": "TERMINOLOGY_ID",
                                                            "value": "local"
                                                        },
                                                        "code_string": "at0005"
                                                    }
                                                },
                                                "archetype_node_id": "at0002",
                                                "value": {
                                                    "_type": "DV_DATE_TIME",
                                                    "value": "2023-02-20T15:45:56.049-03:00"
                                                }
                                            },
                                            {
                                                "_type": "ELEMENT",
                                                "name": {
                                                    "_type": "DV_CODED_TEXT",
                                                    "value": "Date ordered/recommended",
                                                    "defining_code": {
                                                        "terminology_id": {
                                                            "_type": "TERMINOLOGY_ID",
                                                            "value": "local"
                                                        },
                                                        "code_string": "at0003"
                                                    }
                                                },
                                                "archetype_node_id": "at0002",
                                                "value": {
                                                    "_type": "DV_DATE_TIME",
                                                    "value": "2023-02-20T15:45:56.051-03:00"
                                                }
                                            }
```

But, as said, the problem is in the OPT itself.

**Comment by jkryszyn** [comment] 2023-02-21 09:56
@ppazos thank you for your explanation. As I wrote in the first message, this template was downloaded directly from CKM. I don't see any option to leave a comment there, but I think that your comment should be shared somehow with the template creator.

**Comment by ppazos** [comment] 2023-02-21 14:21
@jkryszyn thanks, I thought you were the author! hehe, just checked the OPT and it seems Ian is the author, I commented about the issue here https://discourse.openehr.org/t/found-an-interesting-case-when-an-opt-might-be-invalid-and-i-think-modeling-tools-are-not-checking-it/3594/3

Even though there is an issue in the OPT, I found an extra check that should be added to the instance generator that is related with this issue but won't solve it since the OPT needs to change.

**Comment by ppazos** [comment] 2023-02-22 04:25
We have tested with an updated version of the OPT, just removing some options for the codes in the name to avoid the intersection of those lists and added a fix to the occurrences validator https://github.com/ppazos/openEHR-OPT/commit/abb51bfb46658c15c4c7180faa0ba1c2f492e74e

But can't do much about the OPT itself, it needs to be fixed by the author (see discourse link)

**Closed by ppazos** 2023-02-22 04:25 UTC
Labels: test
